import { webkit } from 'playwright';
const browser = await webkit.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.addInitScript(() => { const p = HTMLMediaElement.prototype.play; HTMLMediaElement.prototype.play = function () { this.muted = true; this.volume = 0; return p.call(this); }; });
const erros = [];
page.on('pageerror', e => erros.push('PAGEERROR ' + e.message));
page.on('console', m => { if (m.type() !== 'log') erros.push(m.type() + ' ' + m.text().slice(0, 200)); });
await page.goto('https://bancada-6x9.pages.dev/');
await page.waitForSelector('#professores button');
await page.waitForTimeout(1500);
console.log('iniciar terminou?', await page.evaluate(() => ({ bancada: !!window.__bancada, chipCodec: document.querySelector('#chipCodec').textContent, chipGroq: document.querySelector('#chipGroq').className })));
const base = new URL('../teste/', import.meta.url).pathname;
await page.setInputFiles('#arquivos', [base + '01.mp4']);
await page.waitForTimeout(3000);
console.log('após setInputFiles:', await page.evaluate(() => ({ files: document.querySelector('#arquivos').files.length, fase: window.__E.fase })));
await page.evaluate(() => document.querySelector('#arquivos').dispatchEvent(new Event('change', { bubbles: true })));
await page.waitForTimeout(3000);
console.log('após change manual:', await page.evaluate(() => ({ fase: window.__E.fase, etapas: [...document.querySelectorAll('#etapas li')].map(l => l.className + ':' + l.textContent).join(' | ') })));
console.log('mensagens:', erros.length ? erros.join(' || ') : 'nenhuma');
await browser.close();
